name: smart_work
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  loading_indicator: ^3.1.1
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  flutter_bloc: ^8.1.3
  flutter_advanced_drawer: ^1.3.5
  intl: ^0.18.1
  bloc: ^8.1.2
  get_it: ^7.6.4
  dio: ^5.3.3
  awesome_dio_interceptor: ^1.0.0
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  badges: ^3.1.2
  syncfusion_flutter_calendar: ^23.1.43
  firebase_core: ^2.21.0
  flutter_local_notifications: ^16.1.0
  firebase_messaging: ^14.7.3
  syncfusion_flutter_sliders: ^23.1.43
  syncfusion_flutter_core: ^23.1.43
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_analog_clock: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/on_boarding/
    - assets/icons/
    - assets/icons/types/
    - assets/icons/app/
    - assets/icons/about/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/sf_pro/SFPRODISPLAYMEDIUM.OTF
          weight: 300
        - asset: assets/fonts/sf_pro/SFPRODISPLAYREGULAR.OTF
          weight: 500
        - asset: assets/fonts/sf_pro/SFPRODISPLAYBOLD.OTF
          weight: 900
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Regular.ttf
        - asset: assets/fonts/Inter/static/Inter-SemiBold.ttf
          weight: 700
        - asset: assets/fonts/Inter/static/Inter-Bold.ttf
          weight: 900
        - asset: assets/fonts/Inter/static/Inter-Bold.ttf
          weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
